version: '3'
services:
  orchestrator:
    build:
      context: . # Set working directory (vbm/cat12/)
      dockerfile: ./test/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
